# Nome da aplicação
spring.application.name=LojaCell

# Conexão com o Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/lojacell_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Flyway (Migração)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Exibir os SQLs no console (bom para aprender o que o JPA está fazendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração de Upload (Caminho no seu PC)
lojacell.upload.directory=C:/devJava/lojacell-uploads

# Limites de tamanho (O Spring barra arquivos gigantes que travam o PC)

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB

